language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services: mongodb

before_script:
  - composer install --dev --no-interaction --prefer-source

notifications:
  irc:
    channels:
      - "chat.freenode.net#mongofill"
    template:
      - "%{repository} (%{commit}) : %{message} (%{author})"
      - "Build details: %{build_url} (%{duration})" 
